export const january = [
    {
      id: 1,
      name: "Ajayi Olumide",
      birthday: "january 14th ",
      department: "",
      image: "assets/INNOVA.jpg",
      contact: "08181445383",
    },
    {
      id: 2,
      name: "David Greatness",
      birthday: "january 12th",
      department: "",
      image: "",
      contact: "08089637328",
    },
    {
      id: 3,
      name: "Oyeniran Biliki",
      birthday: "January 16th",
      department: "Good Women",
      image: "",
      contact: "08028286949",
    },
    {
      id: 4,
      name: "Oluwaseun Adedeji",
      birthday: "january 7th",
      department: "",
      image: "",
      contact: "07031217114",
    },
    {
      id: 5,
      name: "Adele Tolulope",
      birthday: "January 16th ",
      department: "Choir",
      image: "",
      contact: "08024662122",
    },
    {
      id: 6,
      name: "Usman Opeoluwa",
      birthday: "January 24th",
      department: "Children Church",
      image: "",
      contact: "08088929251",
    },
    {
      id: 7,
      name: "Oyeniran Oluwafemi",
      birthday: "January 11th",
      department: "Technical Department",
      image: "",
      contact: "08075054157",
    },
    {
      id: 8,
      name: "chika okechukwu",
      birthday: "January 25th",
      department: "",
      image: "",
      contact: "08164528851",
    },
    {
      id: 9,
      name: "Adeola Osagie",
      birthday: "January 6th",
      department: "",
      image: "",
      contact: "08022519576",
    },
    {
      id: 10,
      name: "Otele Esther",
      birthday: "January 3rd",
      department: "",
      image: "",
      contact: "08027627969, 0705130060",
    },
  ];
  export const february = [
    {
      id: 1,
      name: "Mary Precious",
      birthday: "february 22",
      department: "",
      image: "",
      contact: "09162212294",
    },
  
    {
      id: 2,
      name: "",
      birthday: "",
      department: "",
      image: "",
    },
  ];
  export const march = [
    {
      id: 1,
      name: "ADEYEYE BLESSING",
      birthday: "10th MARCH",
      department: "",
      image: "",
      contact: "07060892222",
    },
    {
        id: 2,
        name: "ADENIYI OLAYINKA",
        birthday: "12th MARCH",
        department: "",
        image: "",
        contact: "08141115812",
      },
      {
        id: 3,
        name: "OLUWATIMILEHIN STEPHEN TOPE",
        birthday: "21st MARCH",
        department: "",
        image: "",
        contact: "07084372867",
      },
      {
        id: 4,
        name: "ADEBANJO OLUWAFEMI BENJAMIN",
        birthday: "11th MARCH",
        department: "",
        image: "",
        contact: "08071105594",
      },
      {
        id: 5,
        name: "ADEBAYO OYINKANSADE",
        birthday: "16th MARCH",
        department: "",
        image: "",
        contact: "07036596622",
      },
      {
        id: 6,
        name: "OGUNBARE IBUKUNOLUA",
        birthday: "7th MARCH",
        department: "",
        image: "",
        contact: "08068800483",
      },
      {
        id: 7,
        name: "AKINLUSI FUNSO OLUWAGBEMIGA",
        birthday: "MARCH",
        department: "",
        image: "",
        contact: "09065744501",
      },
  ];
  export const april = [
    {
      id: 1,
      name: "ODUNOWO BOLUWATIFE",
      birthday: "25th APRIL",
      department: "",
      image: "",
      contact: "09050362226",
    },
    {
        id: 2,
        name: "ODE DAVID",
        birthday: "2th APRIL",
        department: "",
        image: "",
        contact: "08144666135",
      },
      {
        id: 3,
        name: "OYEFESO ",
        birthday: "APRIL",
        department: "",
        image: "",
        contact: "08123854688",
      },
      {
        id: 4,
        name: "BUNMI ADESANYA",
        birthday: "22nd APRIL",
        department: "",
        image: "",
        contact: "08187722176",
      },
      {
        id: 5,
        name: "DCNS ADEWUNMI ABIKE SULE",
        birthday: "4th APRIL",
        department: "",
        image: "",
        contact: "09083619514",
      },
      {
        id: 6,
        name: "OLUMIDE OMOLARA",
        birthday: "8th APRIL",
        department: "",
        image: "",
        contact: "09152033899",
      },
      {
        id: 7,
        name: "MRS. AJIMALUFIN ",
        birthday: "13th APRIL",
        department: "",
        image: "",
        contact: "07084952565",
      },
      {
        id: 8,
        name: "SIS. FLORENCE OZOR",
        birthday: "29th APRIL",
        department: "",
        image: "",
        contact: "09076337258",
      },
      {
        id: 9,
        name: "ONOYIBO PATIENCE",
        birthday: "29th APRIL",
        department: "",
        image: "",
        contact: "07068690234",
      },
      {
        id: 10,
        name: "BAKARE ESTHER",
        birthday: "15th APRIL",
        department: "",
        image: "",
        contact: "08163592398",
      },
      {
        id: 11,
        name: "IGIRI RHODA",
        birthday: "APRIL",
        department: "",
        image: "",
        contact: "09136208817",
      },
      {
        id: 12,
        name: "AFUYE KAYODE",
        birthday: "10th APRIL",
        department: "",
        image: "",
        contact: "08037763048",
      },
      {
        id: 13,
        name: "DAVID",
        birthday: "25th APRIL",
        department: "",
        image: "",
        contact: "08144666135",
      },
      {
        id: 14,
        name: "VICIENT OKEIZE PATIENCE",
        birthday: "4th APRIL",
        department: "",
        image: "",
        contact: "08060670416",
      },
  ];
  export const may = [
    {
      id: 1,
      name: "OKOR PATIENCE",
      birthday: "9th MAY",
      department: "",
      image: "",
      contact: "08065009922",
    },
    {
        id: 2,
        name: "ODUNSI ADURAGBEMI",
        birthday: "23th MAY",
        department: "",
        image: "",
        contact: "08135761170",
      },
      {
        id: 3,
        name: "AKINKUOWO VICTOR",
        birthday: "19th MAY",
        department: "",
        image: "",
        contact: "08105391267",
      },
      {
        id: 4,
        name: "EMMANUEL SANDRA",
        birthday: "8th MAY",
        department: "",
        image: "",
        contact: "09137663647",
      },
      {
        id: 5,
        name: "KUYORO DAMILOLA",
        birthday: "25th MAY",
        department: "",
        image: "",
        contact: "08075354566",
      },
      {
        id: 6,
        name: "AJOMOLE TEMITOPE",
        birthday: "27th MAY",
        department: "",
        image: "",
        contact: "08034313185",
      },
      {
        id: 7,
        name: "YINKA ABIBAT",
        birthday: "18th MAY",
        department: "",
        image: "",
        contact: "09068863259",
      },
      {
        id: 8,
        name: "MRS. ODUGBEMI",
        birthday: "20th MAY",
        department: "",
        image: "",
        contact: "0",
      },
      {
        id: 9,
        name: "SEGUN AJAKAYE",
        birthday: "11th MAY",
        department: "",
        image: "",
        contact: "0705555853",
      },
      {
        id: 10,
        name: "ADEOYE TITILAYO",
        birthday: "1st MAY",
        department: "",
        image: "",
        contact: "09035827819",
      },
      {
        id: 11,
        name: "MR. BELIEVE OKORONKWO",
        birthday: "28th MAY",
        department: "",
        image: "",
        contact: "07061850816",
      },
      {
        id: 12,
        name: "JOSHUA BAKARE",
        birthday: "6th MAY",
        department: "",
        image: "",
        contact: "08062816786",
      },
      {
        id: 13,
        name: "0LAOYE .O PETER",
        birthday: "MAY",
        department: "",
        image: "",
        contact: "0708099000",
      },

      {
        id: 14,
        name: "SIS. ADEOSU ONOTAYO",
        birthday: "3rd MAY",
        department: "",
        image: "",
        contact: "08138765104",
      },
  ];
  export const june = [
    {
      id: 1,
      name: "AFOLABI AYODEJI",
      birthday: "21st JUNE",
      department: "",
      image: "",
      contact: "08163992211",
    },
    {
        id: 2,
        name: "OBASEGUN SEGUN",
        birthday: "2nd JUNE",
        department: "",
        image: "",
        contact: "07063300606",
      },
      {
        id: 3,
        name: "BOYEJO OLUWATOSIN",
        birthday: "13th JUNE",
        department: "",
        image: "",
        contact: "0803437345",
      },
      {
        id: 4,
        name: "BANJO ADESOLA",
        birthday: "15th JUNE",
        department: "",
        image: "",
        contact: "08133717383",
      },
      {
        id: 5,
        name: "YETUNDE OLAOYE",
        birthday: "13th JUNE",
        department: "",
        image: "",
        contact: "09037492887",
      },
      {
        id: 6,
        name: "AFUYE VICTORIA",
        birthday: "30th JUNE",
        department: "",
        image: "",
        contact: "07030149350",
      },
      {
        id: 7,
        name: "OYELAKIN IFEOLUWA",
        birthday: "10th JUNE",
        department: "",
        image: "",
        contact: "08152888405",
      },
      {
        id: 8,
        name: "MRS. ADEJOKE SONUBI",
        birthday: "12t JUNE",
        department: "",
        image: "",
        contact: "080261315191",
      },
      {
        id: 9,
        name: "AMUSA ESTHER",
        birthday: "7th JUNE",
        department: "",
        image: "",
        contact: "09046538051",
      },
      {
        id: 10,
        name: "ELEGBEDE DEBORAH. O",
        birthday: "18th JUNE",
        department: "",
        image: "",
        contact: "08076342049",
      },
      {
        id: 11,
        name: "TOLULOPE ADELE",
        birthday: "16th JUNE",
        department: "",
        image: "",
        contact: "08025662122",
      },
      {
        id: 12,
        name: "MRS. EDIBO ",
        birthday: "5th JUNE",
        department: "",
        image: "",
        contact: "09153270998",
      },
      {
        id: 13,
        name: "ONAFOWOPE OLUWANIFEMI",
        birthday: "23rd JUNE",
        department: "",
        image: "",
        contact: "08023177541",
      },
      {
        id: 14,
        name: "MUMY AFUYE SABOINACH",
        birthday: "JUNE",
        department: "",
        image: "",
        contact: "08023177541",
      },
      {
        id: 15,
        name: "ADESANYA ADEOLA HAMMED",
        birthday: "14th JUNE",
        department: "",
        image: "",
        contact: "08131971762",
      },
  ];
  export const july = [
    {
      id: 1,
      name: "HASSAN OLUWASEUN",
      birthday: "28th JULY",
      department: "",
      image: "",
      contact: "08183434915",
    },
    {
        id: 2,
        name: "OBASEGUN HELEN",
        birthday: "3rd JULY",
        department: "",
        image: "",
        contact: "07063300606",
      },
      {
        id: 3,
        name: "AKINDELE ONI ENOCH AJANAKU",
        birthday: "13t JULY",
        department: "",
        image: "",
        contact: "08105361201",
      },
      {
        id: 4,
        name: "ASHIRU GBOLAHAN",
        birthday: "24th JULY",
        department: "",
        image: "",
        contact: "09013957935",
      },
      {
        id: 5,
        name: "AKINLUSI IYIOLA ADEBAYO",
        birthday: "28th JULY",
        department: "",
        image: "",
        contact: "0814668773",
      },
  ];
  export const august = [
    {
      id: 2,
      name: "",
      birthday: "",
      department: "",
      image: "",
    },
  ];
  export const september = [
    {
      id: 2,
      name: "",
      birthday: "",
      department: "",
      image: "",
    },
  ];
  export const october = [
    {
      id: 2,
      name: "",
      birthday: "",
      department: "",
      image: "",
    },
  ];
  export const november = [
    {
      id: 2,
      name: "",
      birthday: "",
      department: "",
      image: "",
    },
  ];
  export const december = [
    {
      id: 2,
      name: "",
      birthday: "",
      department: "",
      image: "",
    },
  ];